name: Auto Build and Release
on:
  push:
    branches:
      - master
      - release-v1.19.9
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set_timestamp.outputs.timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set timestamp
        id: set_timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          npm run zipdist

      - name: Set version output
        id: set_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist/
            dist.zip

  draft_release:
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:  # 添加权限声明11
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}  # 使用默认 Token 或替换为 MY_TOKEN
        with:
          files: dist.zip
          tag_name: v1.19.9+${{ needs.build-and-release.outputs.timestamp }}
          target_commitish: ${{ github.sha }}  # 精确绑定到触发工作流的提交
          draft: false
          make_latest: ${{ github.ref_name == 'main' }}
          prerelease: false
          generate_release_notes: true